# Generated by Django 4.0.2 on 2022-02-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Senryu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(null=True, verbose_name='uid')),
                ('name', models.CharField(default='', max_length=30, verbose_name='雅号')),
                ('ku1', models.CharField(max_length=30, verbose_name='初句')),
                ('ku2', models.CharField(max_length=30, verbose_name='二句')),
                ('ku3', models.CharField(max_length=30, verbose_name='結句')),
                ('comment', models.TextField(null=True, verbose_name='コメント')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '川柳',
                'verbose_name_plural': '川柳',
                'db_table': 'senryu',
            },
        ),
    ]
